### ISSUE TITLE
Zoomen op (kleine) touch devices werkt niet

### ISSUE THREAD

**Issue by KrijnHoetmer** [MartijnNieuwenhuizen/Browser_Technologies#1]
Waarom mag ik niet zoomen? :) (En waarom zit er wat witruimte rechts op een iPhone?)

**Comment by MartijnNieuwenhuizen** [comment]
De witruimte was een css foutje (is gefixed). Het zoomen heb ik onbewust uitgezet in de meta tag.
De code was `<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">` en is nu `<meta name="viewport" content="width=device-width, initial-scale=1">`. De `maximum-scale=1` betekend dat je niet mag zoomen. Heb ik dom overgenomen uit een vorig bestand en is uiteraard in bijde bestanden verwijderd, zie commit.

**Comment by KrijnHoetmer** [comment]
Top! Pas op met copy & paste dus! :)

**Comment by KoopReynders** [comment]
done
