### ISSUE TITLE
Niet voor alle APIs heb je een feature detect gedaan

### ISSUE THREAD

**Issue by KrijnHoetmer** [MartijnNieuwenhuizen/Browser_Technologies#2]
In principe goed dat je een cutting the mustard techniek gebruikt voor `querySelector` en `addEventListener`, maar je gebruikt in je code wel meer APIs die je dus voor lief neemt met die check. Wat gebeurt er bijvoorbeeld in IE9?

**Comment by MartijnNieuwenhuizen** [comment]
Jammer dat IE9 de classList niet ondersteund! De check is toegevoegd.

**Comment by KrijnHoetmer** [comment]
Pas wel op met deze manier, want volgens mij levert die fouten op in browsers die classList niet ondersteunen. Even checken hoe je classList correct detect!

**Comment by KoopReynders** [comment]
done?

**Comment by MartijnNieuwenhuizen** [comment]
Getest in IE9, waarin de classList niet werkt volgens CanIUse.
De check werkt en er komen hier geen Errors op, dus Done :)
![screen shot 2016-05-20 at 18 04 21](https://cloud.githubusercontent.com/assets/6492909/15434115/b1fe3d4c-1eb5-11e6-9681-e216a8017cd1.png)
