### ISSUE TITLE
Voor welke browsers is filter: alpha();?

### ISSUE THREAD

**Issue by KrijnHoetmer** [MartijnNieuwenhuizen/Browser_Technologies#3]
Voor welke browsers heb je `filter: alpha(...);` toegevoegd? Wel benieuwd naar de redenering daarachter.

**Comment by MartijnNieuwenhuizen** [comment]
Helaas is dit de magie van Gulp. Ik heb het gebruikt om de css automatisch te prefixen, hij maakt dan van `opacity: 1;` `filter: alpha(opacity=100);`. De prefixer gebruikt dit om transparantie in IE8 mogenlijk te maken, [Can I use: Opacity](http://caniuse.com/#feat=css-opacity). Ik gebruik het daarintegen om een element niet te tonen, dus dit zijn 4 regels nuttelose css. Het is eruit gehaald in de niewste commit. 
@krijnhoetmer Hoe prefix jij je code? Ik zou graag iets willen waar ik een beter overzich over heb maar het niet met de hand hoef te doen.

**Comment by KrijnHoetmer** [comment]
Voornamelijk met Autoprefixer tegenwoordig, als ik het überhaupt al gebruik. Je moet toch ook nadenken over de gevallen waarbij zelfs de prefixed property niet ondersteund wordt, dus dat wil je sowieso in je code verwerken (ik probeer me niet heel erg druk te maken om wat Can I Use zegt, maar me in te denken wat er gebeurt als een regel CSS niet ondersteund wordt). Prefixen doe ik meestal echt pas als laatste stap, om nog een paar browsers extra mee te krijgen. Maar in het geval van `opacity: 0;`; vraag je af wat je daar doet, en voeg bijvoorbeeld ook `visibility: hidden;` toe voor browsers die `opacity` niet ondersteunen.

Belangrijker: kijk naar wat tools voor je doen en beoordeel of ze zinvol zijn niet. Tools zijn ook gewoon gemaakt door mensen en bevatten dus ook bugs. In dit geval; hoe zinvol is het om een `filter: alpha(opacity=100);` (specifiek voor oude IE's) in een keyframe animation te zetten (die oude IE's sowieso al niet ondersteunen)? Volgens mij vangt Autoprefixer dit laatste wel goed af, maar dat weet ik niet zeker.

**Comment by MartijnNieuwenhuizen** [comment]
Ik heb het nog een keer gecheked, ik heb geen Gulp prefixer gebruikt maar een online tool. Gulp prefixed niet voor zulke oude browsers als je het niet zelf insteld.

Maar thx voor de tip!

**Comment by KoopReynders** [comment]
done
