### ISSUE TITLE
Waarom een paar verschillende dirs met stappen?

### ISSUE THREAD

**Issue by KrijnHoetmer** [MartijnNieuwenhuizen/Browser_Technologies#4]
Handig om de voortgang te zien, maar maak het voor jezelf in de toekomst makkelijker (zeker als je PHP gebruikt) door modulair assets aan of uit te zetten in je uiteindelijke HTML. Maak het bijvoorbeeld zo dat je `?nocss` aan je URL toe kunt voegen en voeg een simpele `if (!isset($_GET['nocss'])) { ... }` check toe waar je je `<link>` plaatst. Op die manier kun je je HTML nog verbeteren en toch de versie zonder CSS of JS testen/tonen. Het gebeurt namelijk bijna nooit dat je teruggaat naar je vorige demo's om de HTML daar ook alsnog aan te passen.

**Comment by MartijnNieuwenhuizen** [comment]
Thx voor de tip, ga ik volgende keer zo aanpakken!

**Comment by KoopReynders** [comment]
done
