### ISSUE TITLE
Nog 1 ontbrekende stap in concept

### ISSUE THREAD

**Issue by KrijnHoetmer** [MartijnNieuwenhuizen/Browser_Technologies#5]
Daar waar je nu je drop handler hebt, en `newListItem` aanmaakt in JS; zou het niet heel tof (en handig) zijn als je daar gewoon je back-end code kunt gebruiken? Een behoorlijk grote stap verder, maar op die manier maak je gebruik van code die je sowieso al hebt. Stel dat er allerlei spannende dingen op de server gebeuren (filteren, sorteren, voorraadbeheer, weet ik het), dan wil je dat eigenlijk maar op één plek doen, en eigenlijk wil je je enhancement laten profiteren van dat idee. Je zou dus onder water een POST kunnen doen na drag & drop en de response daarvan kunnen gebruiken om de lijst te vullen. Zie bijvoorbeeld http://bulletproofajax.com/code/ (concept van Chapter 8).

**Comment by MartijnNieuwenhuizen** [comment]
Ja, daar heb ik nog nooit aan gedacht, maar is erg vet. Waarom verdelen als het ook helemaal op de server kan. 
Ik heb geprobeerd het te maken, de Call wordt ook gemaakt, maar ik weet niet hoe/of ik dit met php kan opvangen en dan weer kan tonen zonder een page refresh te doen. Ik wil geen page request doen omdat het hele effect dan weg is. Ook moet je dan checken en opslaan bij welke stap de user was, al met al lijkt me dat verwarrend voor de gebruiker.
Met Node zou ik het kunnen, maar ga er morgen nog even naar kijken, hopelijk lukt het!

**Comment by MartijnNieuwenhuizen** [comment]
De date wordt nu aan de lijst toegevoegd in de POST request. De data wordt ook naar de goede php file (server) gestuurd. Ik krijg alleen de return niet goed. Als ik vanaf de server.php een string echo komt die binnen als response op de POST request, maar ik kan niet de data die met de POST is gestuurd terug loggen. Vandaar deze oplossing.

**Comment by KoopReynders** [comment]
done
