### ISSUE TITLE
Opdracht, presentatie & readme

### ISSUE THREAD

**Issue by KoopReynders** [MartijnNieuwenhuizen/Browser_Technologies#6]
Wat ik mis in je Readme is een gestructureerde opbouw van je verhaal.
B.v. beginnen met wát de opdracht/demo is, welke hippe API je daarvoor gaat gebruiken/onderzoeken, en dan stap voor stap hoe je de PE hebt gedaan ...

Readme mist een duidelijk opbouw. Zie Moodle voor oplevercriteria.

**Comment by MartijnNieuwenhuizen** [comment]
De readme is uitgebreid aan de hand van de hand van de feedback en de criteria.

**Comment by KoopReynders** [comment]
done
